version: '3.3'

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ../backend/.env
  backend:
    image: daniilpanyushin/foodgram_backend:0.3
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_files:/code/static/
      - media_files:/code/media/
    depends_on:
      - db
    env_file:
      - ../backend/.env
  frontend:
    image: daniilpanyushin/foodgram_frontend:0.3
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_files:/var/html/static/
      - media_files:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_files:
  media_files:
